export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "Flutter"
  | "Dart"
  | "Flask"
  | "Django"
  | "FastAPI"
  | "SQL"
  | "NoSQL"
  | "Framer Motion"
  | "Scikitlearn"
  | "Numpy"
  | "Pandas"
  | "MLflow"
  | "Matplotlib"
  | "MCMC"
  | "C"
  | "C++"
  | "Python"
  | "Embedded C"
  | "Optimization"
  | "Regression"
  | "Seaborn"
  | "NLTK"
  | "TF-IDF"
  | "ML/DS"
  | "Statsmodels"
  | "pmdarima"
  | "Streamlit"
  | "D-Wave"
  | "Quantum Annealing"
  | "ML"
  | "RBM"
  | "PyTorch"
  | "TensorFlow"
  | "YOLOv3"
  | "OpenCV"
  | "Computer Vision"
  | "NLP"
  ;

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "3D Modeling"
  | "ML/DS"
  | "Data Scientist / Machine Learning Engineer"
  | "NLP"
  | "Regression"
  | "Classification"
  | "Data Science"
  | "Time Series"
  | "Forecasting"
  | "Recommendation Systems"
  | "ML"
  | "Quantum Computing"
  | "Generative Models"
  | "Continual Learning"
  | "Generative Models"
  | "Predictive Modeling"
  | "Decision Trees"
  | "Computer Vision"
  |  "Object Detection"
  | "Scikit-learn"
  | "NumPy"
  | "Matplotlib"
  | "Seaborn";

export type ValidExpType = "Personal" | "Academic";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "resume";
